### PR TITLE
fix: update moon and packemon

### LINKED ISSUE #5: update moon and packemon

### PR DESCRIPTION
**Pull request by azu**
Remove Dynamic Import workaround
https://github.com/milesj/packemon/issues/138

fix #5

### CODE REVIEW

File: packages/core/src/index.ts [hunk 1]
```diff
@@ -35,16 +35,14 @@ export type CreateCacheOptions = {
...
-const _importDynamic = new Function("modulePath", "return import(modulePath)");
 export type DeleteCacheOptions = Omit<CreateCacheOptions, "noCache">;
 /**
  * Delete cache file
  * Note: It does not clear in-memory cache in the cache.
  * @param options
  */
 export const deleteCacheFile = async (options: DeleteCacheOptions) => {
-    const { packageDirectory } = await _importDynamic("pkg-dir");
+    const { packageDirectory } = await import("pkg-dir");
```
Comment (azu) [inline packages/core/src/index.ts:45]: cjs

**Comment by azu** [comment]
https://github.com/azu/file-cache/runs/7665518520?check_suite_focus=true
moon ci is unstable?
